default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: sensifydemoapp_development

test:
  <<: *default
  database: sensifydemoapp_test

production:
  <<: *default
  database: sensifydemoapp_production
  username: sensifydemoapp
  password: <%= ENV['SENSIFYDEMOAPP_DATABASE_PASSWORD'] %>
